//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTRServices.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public int account_key { get; set; }
        public int index_key { get; set; }
        public string account_number { get; set; }
        public string account_description { get; set; }
        public string account_number_description { get; set; }
        public Nullable<decimal> account_balance { get; set; }
    
        public virtual index index { get; set; }
    }
}
