//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTRServices.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BtrDbContext : DbContext
    {
        public BtrDbContext()
            : base("name=BtrDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<approval_matrix> approval_matrix { get; set; }
        public virtual DbSet<approval_status> approval_status { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<index> indices { get; set; }
        public virtual DbSet<job> jobs { get; set; }
        public virtual DbSet<program> programs { get; set; }
        public virtual DbSet<responsibility_matrix> responsibility_matrix { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<available_balances> available_balances { get; set; }
        public virtual DbSet<budget_transfer_request> budget_transfer_request { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<xref_budget_type> xref_budget_type { get; set; }
        public virtual DbSet<xref_internal_state> xref_internal_state { get; set; }
        public virtual DbSet<xref_life_cycle> xref_life_cycle { get; set; }
        public virtual DbSet<Audit> Audits { get; set; }
        public virtual DbSet<vw_budget_transfer_request_records> vw_budget_transfer_request_records { get; set; }
        public virtual DbSet<xref_transfer_type> xref_transfer_type { get; set; }
        public virtual DbSet<transfer_activity> transfer_activity { get; set; }
        public virtual DbSet<xref_position_type> xref_position_type { get; set; }
        public virtual DbSet<vw_transfer_activities_datarecords> vw_transfer_activities_datarecords { get; set; }
    
        public virtual ObjectResult<account_byId_Result> account_byId(Nullable<int> account_key)
        {
            var account_keyParameter = account_key.HasValue ?
                new ObjectParameter("account_key", account_key) :
                new ObjectParameter("account_key", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<account_byId_Result>("account_byId", account_keyParameter);
        }
    
        public virtual ObjectResult<account_byIndex_Result> account_byIndex(Nullable<int> index_key)
        {
            var index_keyParameter = index_key.HasValue ?
                new ObjectParameter("index_key", index_key) :
                new ObjectParameter("index_key", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<account_byIndex_Result>("account_byIndex", index_keyParameter);
        }
    
        public virtual ObjectResult<accountbalance_byaccountkey_Result> accountbalance_byaccountkey(Nullable<int> account_key)
        {
            var account_keyParameter = account_key.HasValue ?
                new ObjectParameter("account_key", account_key) :
                new ObjectParameter("account_key", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<accountbalance_byaccountkey_Result>("accountbalance_byaccountkey", account_keyParameter);
        }
    
        public virtual ObjectResult<accountbalance_byaccountkey_Result> accountbalances_byindexkeys(string indexKeys)
        {
            var indexKeysParameter = indexKeys != null ?
                new ObjectParameter("indexKeys", indexKeys) :
                new ObjectParameter("indexKeys", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<accountbalance_byaccountkey_Result>("accountbalances_byindexkeys", indexKeysParameter);
        }
    
        public virtual ObjectResult<accounts_all_Result> accounts_all()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<accounts_all_Result>("accounts_all");
        }
    
        public virtual ObjectResult<approval_matrix_all_approvers_Result> approval_matrix_all_approvers(Nullable<int> index_key)
        {
            var index_keyParameter = index_key.HasValue ?
                new ObjectParameter("index_key", index_key) :
                new ObjectParameter("index_key", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<approval_matrix_all_approvers_Result>("approval_matrix_all_approvers", index_keyParameter);
        }
    
        public virtual ObjectResult<approval_matrix_approver_Result> approval_matrix_approver(Nullable<int> index_key, string role_level)
        {
            var index_keyParameter = index_key.HasValue ?
                new ObjectParameter("index_key", index_key) :
                new ObjectParameter("index_key", typeof(int));
    
            var role_levelParameter = role_level != null ?
                new ObjectParameter("role_level", role_level) :
                new ObjectParameter("role_level", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<approval_matrix_approver_Result>("approval_matrix_approver", index_keyParameter, role_levelParameter);
        }
    
        public virtual ObjectResult<indices_all_Result> indices_all()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<indices_all_Result>("indices_all");
        }
    
        public virtual ObjectResult<indices_bydept_Result> indices_bydept(Nullable<int> dept)
        {
            var deptParameter = dept.HasValue ?
                new ObjectParameter("dept", dept) :
                new ObjectParameter("dept", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<indices_bydept_Result>("indices_bydept", deptParameter);
        }
    
        public virtual ObjectResult<indices_byowner_Result> indices_byowner(string uni)
        {
            var uniParameter = uni != null ?
                new ObjectParameter("uni", uni) :
                new ObjectParameter("uni", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<indices_byowner_Result>("indices_byowner", uniParameter);
        }
    
        public virtual ObjectResult<indices_owned_bydept_Result> indices_owned_bydept(Nullable<int> dept, string uni)
        {
            var deptParameter = dept.HasValue ?
                new ObjectParameter("dept", dept) :
                new ObjectParameter("dept", typeof(int));
    
            var uniParameter = uni != null ?
                new ObjectParameter("uni", uni) :
                new ObjectParameter("uni", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<indices_owned_bydept_Result>("indices_owned_bydept", deptParameter, uniParameter);
        }
    
        public virtual ObjectResult<budget_transfer_request_datarecord_Result> budget_transfer_request_datarecord(Nullable<int> btr_key)
        {
            var btr_keyParameter = btr_key.HasValue ?
                new ObjectParameter("btr_key", btr_key) :
                new ObjectParameter("btr_key", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<budget_transfer_request_datarecord_Result>("budget_transfer_request_datarecord", btr_keyParameter);
        }
    
        public virtual int budget_transfer_request_display(Nullable<int> btr_key)
        {
            var btr_keyParameter = btr_key.HasValue ?
                new ObjectParameter("btr_key", btr_key) :
                new ObjectParameter("btr_key", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("budget_transfer_request_display", btr_keyParameter);
        }
    
        public virtual ObjectResult<budget_transfer_request_datarecords_Result> budget_transfer_request_datarecords()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<budget_transfer_request_datarecords_Result>("budget_transfer_request_datarecords");
        }
    
        public virtual ObjectResult<budget_transfer_request_create_Result> budget_transfer_request_create(string title, string budget_type, Nullable<decimal> total_amount, string explanation, string requestor_uni, string transfer_type, string created_by_name)
        {
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            var budget_typeParameter = budget_type != null ?
                new ObjectParameter("budget_type", budget_type) :
                new ObjectParameter("budget_type", typeof(string));
    
            var total_amountParameter = total_amount.HasValue ?
                new ObjectParameter("total_amount", total_amount) :
                new ObjectParameter("total_amount", typeof(decimal));
    
            var explanationParameter = explanation != null ?
                new ObjectParameter("explanation", explanation) :
                new ObjectParameter("explanation", typeof(string));
    
            var requestor_uniParameter = requestor_uni != null ?
                new ObjectParameter("requestor_uni", requestor_uni) :
                new ObjectParameter("requestor_uni", typeof(string));
    
            var transfer_typeParameter = transfer_type != null ?
                new ObjectParameter("transfer_type", transfer_type) :
                new ObjectParameter("transfer_type", typeof(string));
    
            var created_by_nameParameter = created_by_name != null ?
                new ObjectParameter("created_by_name", created_by_name) :
                new ObjectParameter("created_by_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<budget_transfer_request_create_Result>("budget_transfer_request_create", titleParameter, budget_typeParameter, total_amountParameter, explanationParameter, requestor_uniParameter, transfer_typeParameter, created_by_nameParameter);
        }
    
        public virtual ObjectResult<transfer_activity_create_Result> transfer_activity_create(Nullable<int> btr_key, Nullable<int> position_type_key, Nullable<int> index_key, Nullable<int> account_key, Nullable<decimal> amount, Nullable<int> created_by)
        {
            var btr_keyParameter = btr_key.HasValue ?
                new ObjectParameter("btr_key", btr_key) :
                new ObjectParameter("btr_key", typeof(int));
    
            var position_type_keyParameter = position_type_key.HasValue ?
                new ObjectParameter("position_type_key", position_type_key) :
                new ObjectParameter("position_type_key", typeof(int));
    
            var index_keyParameter = index_key.HasValue ?
                new ObjectParameter("index_key", index_key) :
                new ObjectParameter("index_key", typeof(int));
    
            var account_keyParameter = account_key.HasValue ?
                new ObjectParameter("account_key", account_key) :
                new ObjectParameter("account_key", typeof(int));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(decimal));
    
            var created_byParameter = created_by.HasValue ?
                new ObjectParameter("created_by", created_by) :
                new ObjectParameter("created_by", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<transfer_activity_create_Result>("transfer_activity_create", btr_keyParameter, position_type_keyParameter, index_keyParameter, account_keyParameter, amountParameter, created_byParameter);
        }
    
        public virtual int transfer_activity_delete(Nullable<int> transfer_activity_key)
        {
            var transfer_activity_keyParameter = transfer_activity_key.HasValue ?
                new ObjectParameter("transfer_activity_key", transfer_activity_key) :
                new ObjectParameter("transfer_activity_key", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("transfer_activity_delete", transfer_activity_keyParameter);
        }
    
        public virtual ObjectResult<transfer_activity_update_Result> transfer_activity_update(Nullable<int> transfer_activity_key, Nullable<int> index_key, Nullable<int> account_key, Nullable<decimal> amount, Nullable<int> modified_by)
        {
            var transfer_activity_keyParameter = transfer_activity_key.HasValue ?
                new ObjectParameter("transfer_activity_key", transfer_activity_key) :
                new ObjectParameter("transfer_activity_key", typeof(int));
    
            var index_keyParameter = index_key.HasValue ?
                new ObjectParameter("index_key", index_key) :
                new ObjectParameter("index_key", typeof(int));
    
            var account_keyParameter = account_key.HasValue ?
                new ObjectParameter("account_key", account_key) :
                new ObjectParameter("account_key", typeof(int));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(decimal));
    
            var modified_byParameter = modified_by.HasValue ?
                new ObjectParameter("modified_by", modified_by) :
                new ObjectParameter("modified_by", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<transfer_activity_update_Result>("transfer_activity_update", transfer_activity_keyParameter, index_keyParameter, account_keyParameter, amountParameter, modified_byParameter);
        }
    
        public virtual ObjectResult<budget_transfer_request_update_Result> budget_transfer_request_update(Nullable<int> btr_key, string title, Nullable<int> budget_type_key, Nullable<decimal> total_amount, string explanation, Nullable<int> requestor_uni_key, Nullable<int> transfer_type_key, Nullable<int> life_cycle_key, Nullable<int> modified_by)
        {
            var btr_keyParameter = btr_key.HasValue ?
                new ObjectParameter("btr_key", btr_key) :
                new ObjectParameter("btr_key", typeof(int));
    
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            var budget_type_keyParameter = budget_type_key.HasValue ?
                new ObjectParameter("budget_type_key", budget_type_key) :
                new ObjectParameter("budget_type_key", typeof(int));
    
            var total_amountParameter = total_amount.HasValue ?
                new ObjectParameter("total_amount", total_amount) :
                new ObjectParameter("total_amount", typeof(decimal));
    
            var explanationParameter = explanation != null ?
                new ObjectParameter("explanation", explanation) :
                new ObjectParameter("explanation", typeof(string));
    
            var requestor_uni_keyParameter = requestor_uni_key.HasValue ?
                new ObjectParameter("requestor_uni_key", requestor_uni_key) :
                new ObjectParameter("requestor_uni_key", typeof(int));
    
            var transfer_type_keyParameter = transfer_type_key.HasValue ?
                new ObjectParameter("transfer_type_key", transfer_type_key) :
                new ObjectParameter("transfer_type_key", typeof(int));
    
            var life_cycle_keyParameter = life_cycle_key.HasValue ?
                new ObjectParameter("life_cycle_key", life_cycle_key) :
                new ObjectParameter("life_cycle_key", typeof(int));
    
            var modified_byParameter = modified_by.HasValue ?
                new ObjectParameter("modified_by", modified_by) :
                new ObjectParameter("modified_by", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<budget_transfer_request_update_Result>("budget_transfer_request_update", btr_keyParameter, titleParameter, budget_type_keyParameter, total_amountParameter, explanationParameter, requestor_uni_keyParameter, transfer_type_keyParameter, life_cycle_keyParameter, modified_byParameter);
        }
    }
}
