//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTRServices.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class budget_transfer_request
    {
        public int btr_key { get; set; }
        public System.Guid btr_guid { get; set; }
        public int budget_type_key { get; set; }
        public int life_cycle_key { get; set; }
        public int internal_state_key { get; set; }
        public decimal total_amount { get; set; }
        public string explanation { get; set; }
        public bool priority_flag { get; set; }
        public int requestor_uni_key { get; set; }
        public Nullable<int> transfer_type_key { get; set; }
        public string title { get; set; }
        public System.DateTime modified { get; set; }
        public System.DateTime created { get; set; }
        public int modified_by { get; set; }
        public int created_by { get; set; }
        public string jv_doc_id { get; set; }
        public string jv_status_code { get; set; }
    
        public virtual xref_budget_type xref_budget_type { get; set; }
        public virtual xref_internal_state xref_internal_state { get; set; }
        public virtual xref_life_cycle xref_life_cycle { get; set; }
        public virtual user user { get; set; }
    }
}
