//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTRServices.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int employee_key { get; set; }
        public int job_key { get; set; }
        public string employee_fname { get; set; }
        public string employee_lname { get; set; }
        public string employee_mi { get; set; }
        public string employee_prefix { get; set; }
        public string employee_suffix { get; set; }
        public string employee_name { get; set; }
    }
}
