//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTRServices.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class tc_HRFormsEntities1 : DbContext
    {
        public tc_HRFormsEntities1()
            : base("name=tc_HRFormsEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tc_employee> tc_employee { get; set; }
        public virtual DbSet<tc_otp_payment> tc_otp_payment { get; set; }
        public virtual DbSet<tc_otp_trns> tc_otp_trns { get; set; }
        public virtual DbSet<tc_otp_trns_comments> tc_otp_trns_comments { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    
        public virtual int sp_GET_Employee_By_Uni(string employee_uni)
        {
            var employee_uniParameter = employee_uni != null ?
                new ObjectParameter("employee_uni", employee_uni) :
                new ObjectParameter("employee_uni", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GET_Employee_By_Uni", employee_uniParameter);
        }
    }
}
