//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTRServices.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HrDbContext : DbContext
    {
        public HrDbContext()
            : base("name=HrDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tc_employee> tc_employee { get; set; }
        public virtual DbSet<tc_otp_payment> tc_otp_payment { get; set; }
        public virtual DbSet<tc_otp_trns> tc_otp_trns { get; set; }
        public virtual DbSet<tc_otp_trns_comments> tc_otp_trns_comments { get; set; }
        public virtual DbSet<banner_employee> banner_employee { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    
        public virtual ObjectResult<otp_payment_create_Result> otp_payment_create(Nullable<int> otp_trns_key_id, string otp_trns_payment_index_number, string otp_trns_payment_account_number, Nullable<int> otp_trns_payment_percentage, Nullable<decimal> otp_trns_payment_amount)
        {
            var otp_trns_key_idParameter = otp_trns_key_id.HasValue ?
                new ObjectParameter("otp_trns_key_id", otp_trns_key_id) :
                new ObjectParameter("otp_trns_key_id", typeof(int));
    
            var otp_trns_payment_index_numberParameter = otp_trns_payment_index_number != null ?
                new ObjectParameter("otp_trns_payment_index_number", otp_trns_payment_index_number) :
                new ObjectParameter("otp_trns_payment_index_number", typeof(string));
    
            var otp_trns_payment_account_numberParameter = otp_trns_payment_account_number != null ?
                new ObjectParameter("otp_trns_payment_account_number", otp_trns_payment_account_number) :
                new ObjectParameter("otp_trns_payment_account_number", typeof(string));
    
            var otp_trns_payment_percentageParameter = otp_trns_payment_percentage.HasValue ?
                new ObjectParameter("otp_trns_payment_percentage", otp_trns_payment_percentage) :
                new ObjectParameter("otp_trns_payment_percentage", typeof(int));
    
            var otp_trns_payment_amountParameter = otp_trns_payment_amount.HasValue ?
                new ObjectParameter("otp_trns_payment_amount", otp_trns_payment_amount) :
                new ObjectParameter("otp_trns_payment_amount", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<otp_payment_create_Result>("otp_payment_create", otp_trns_key_idParameter, otp_trns_payment_index_numberParameter, otp_trns_payment_account_numberParameter, otp_trns_payment_percentageParameter, otp_trns_payment_amountParameter);
        }
    
        public virtual int otp_payment_delete_all(Nullable<int> otp_trns_payment_key_id)
        {
            var otp_trns_payment_key_idParameter = otp_trns_payment_key_id.HasValue ?
                new ObjectParameter("otp_trns_payment_key_id", otp_trns_payment_key_id) :
                new ObjectParameter("otp_trns_payment_key_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("otp_payment_delete_all", otp_trns_payment_key_idParameter);
        }
    
        public virtual ObjectResult<otp_payment_update_Result> otp_payment_update(Nullable<int> otp_trns_payment_key_id, Nullable<int> otp_trns_key_id, string otp_trns_payment_index_number, string otp_trns_payment_account_number, Nullable<int> otp_trns_payment_percentage, Nullable<decimal> otp_trns_payment_amount)
        {
            var otp_trns_payment_key_idParameter = otp_trns_payment_key_id.HasValue ?
                new ObjectParameter("otp_trns_payment_key_id", otp_trns_payment_key_id) :
                new ObjectParameter("otp_trns_payment_key_id", typeof(int));
    
            var otp_trns_key_idParameter = otp_trns_key_id.HasValue ?
                new ObjectParameter("otp_trns_key_id", otp_trns_key_id) :
                new ObjectParameter("otp_trns_key_id", typeof(int));
    
            var otp_trns_payment_index_numberParameter = otp_trns_payment_index_number != null ?
                new ObjectParameter("otp_trns_payment_index_number", otp_trns_payment_index_number) :
                new ObjectParameter("otp_trns_payment_index_number", typeof(string));
    
            var otp_trns_payment_account_numberParameter = otp_trns_payment_account_number != null ?
                new ObjectParameter("otp_trns_payment_account_number", otp_trns_payment_account_number) :
                new ObjectParameter("otp_trns_payment_account_number", typeof(string));
    
            var otp_trns_payment_percentageParameter = otp_trns_payment_percentage.HasValue ?
                new ObjectParameter("otp_trns_payment_percentage", otp_trns_payment_percentage) :
                new ObjectParameter("otp_trns_payment_percentage", typeof(int));
    
            var otp_trns_payment_amountParameter = otp_trns_payment_amount.HasValue ?
                new ObjectParameter("otp_trns_payment_amount", otp_trns_payment_amount) :
                new ObjectParameter("otp_trns_payment_amount", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<otp_payment_update_Result>("otp_payment_update", otp_trns_payment_key_idParameter, otp_trns_key_idParameter, otp_trns_payment_index_numberParameter, otp_trns_payment_account_numberParameter, otp_trns_payment_percentageParameter, otp_trns_payment_amountParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_GET_Employee_By_Uni_Result> sp_GET_Employee_By_Uni(string employee_uni)
        {
            var employee_uniParameter = employee_uni != null ?
                new ObjectParameter("employee_uni", employee_uni) :
                new ObjectParameter("employee_uni", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GET_Employee_By_Uni_Result>("sp_GET_Employee_By_Uni", employee_uniParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
