//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTRServices.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class index
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public index()
        {
            this.accounts = new HashSet<account>();
            this.responsibility_matrix = new HashSet<responsibility_matrix>();
            this.approval_matrix = new HashSet<approval_matrix>();
        }
    
        public int index_key { get; set; }
        public string index_coas_code { get; set; }
        public string index_fund_code { get; set; }
        public string index_orgn_code { get; set; }
        public string index_prog_code { get; set; }
        public string index_acct_code { get; set; }
        public string index_actv_code { get; set; }
        public string index_locn_code { get; set; }
        public string index_number { get; set; }
        public string index_description { get; set; }
        public string index_number_description { get; set; }
        public string index_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<account> accounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<responsibility_matrix> responsibility_matrix { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<approval_matrix> approval_matrix { get; set; }
    }
}
