//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTRServices.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class job
    {
        public int job_key { get; set; }
        public Nullable<int> account_key { get; set; }
        public string job_number { get; set; }
        public string job_description { get; set; }
    }
}
