//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTRServices.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tc_employee
    {
        public int employee_key_id { get; set; }
        public string employee_uni { get; set; }
        public string employee_last_name { get; set; }
        public string employee_first_name { get; set; }
        public string employee_position_number { get; set; }
        public string employee_position_description { get; set; }
        public string employee_position_suffix { get; set; }
        public string employee_reports_to_uni { get; set; }
    }
}
