//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTRServices.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tc_otp_trns_comments
    {
        public int otp_trns_comments_key_id { get; set; }
        public Nullable<int> otp_trns_key_id { get; set; }
        public string otp_trns_comments { get; set; }
        public string otp_trns_commentor { get; set; }
        public Nullable<System.DateTime> otp_trns_comments_datetime { get; set; }
    
        public virtual tc_otp_trns tc_otp_trns { get; set; }
    }
}
