//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTRServices.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tc_otp_trns
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tc_otp_trns()
        {
            this.tc_otp_payment = new HashSet<tc_otp_payment>();
            this.tc_otp_trns_comments = new HashSet<tc_otp_trns_comments>();
        }
    
        public int otp_trns_key_id { get; set; }
        public Nullable<int> employee_key_id { get; set; }
        public string otp_trns_reason { get; set; }
        public Nullable<System.DateTime> otp_trns_effective_date { get; set; }
        public string otp_trns_submitter { get; set; }
        public Nullable<bool> otp_trns_processed { get; set; }
        public Nullable<System.DateTime> otp_trns_processed_datatime { get; set; }
    
        public virtual tc_employee tc_employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tc_otp_payment> tc_otp_payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tc_otp_trns_comments> tc_otp_trns_comments { get; set; }
    }
}
