//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTRServices.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class transfer_activity
    {
        public int transfer_activity_key { get; set; }
        public int btr_key { get; set; }
        public int position_type_key { get; set; }
        public Nullable<System.Guid> activity_btr_guid { get; set; }
        public Nullable<System.Guid> activity_item_guid { get; set; }
        public int activity_number { get; set; }
        public int line_number { get; set; }
        public int index_key { get; set; }
        public int account_key { get; set; }
        public string explanation { get; set; }
        public decimal amount { get; set; }
        public int created_by { get; set; }
        public System.DateTime created { get; set; }
        public int modified_by { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string jv_doc_id { get; set; }
        public Nullable<bool> jv_complete { get; set; }
        public string create_jv_error_message { get; set; }
        public string complete_jv_status_message { get; set; }
        public Nullable<int> type_key { get; set; }
        public Nullable<int> status_key { get; set; }
        public Nullable<int> approval_status_key { get; set; }
    }
}
