//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTRServices.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Transfer_Activity_Create_JV
    {
        public string index_number { get; set; }
        public string index_coas_code { get; set; }
        public string index_fund_code { get; set; }
        public string index_orgn_code { get; set; }
        public string account_number { get; set; }
        public string index_prog_code { get; set; }
        public string index_actv_code { get; set; }
        public string index_locn_code { get; set; }
        public string P_dr_cr_ind { get; set; }
        public decimal amount { get; set; }
        public int total_amount { get; set; }
        public string creation_user { get; set; }
        public int transfer_activity_key { get; set; }
        public int btr_key { get; set; }
        public string change_type { get; set; }
    }
}
