//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTRServices.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Indices_lk_all
    {
        public int index_key { get; set; }
        public string index_code { get; set; }
        public string dept_code { get; set; }
        public string index_description { get; set; }
        public string index_code_description { get; set; }
    }
}
