//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTRServices.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Transactions
    {
        public int transfer_activity_key { get; set; }
        public int type_key { get; set; }
        public int status_key { get; set; }
        public int approval_status_key { get; set; }
        public int index_key { get; set; }
        public int account_key { get; set; }
        public Nullable<System.Guid> activity_btr_guid { get; set; }
        public Nullable<System.Guid> activity_row_guid { get; set; }
        public Nullable<System.Guid> activity_item_guid { get; set; }
        public string activity_direction { get; set; }
        public int activity_number { get; set; }
        public int activity_line_number { get; set; }
        public string activity_explanation { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> total_amount { get; set; }
        public string creation_user { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public string modify_user { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string jv_doc_id { get; set; }
        public Nullable<bool> jv_complete { get; set; }
        public string create_jv_error_message { get; set; }
        public string complete_jv_status_message { get; set; }
        public string index_description { get; set; }
        public string index_number_description { get; set; }
        public string account_number { get; set; }
        public string account_description { get; set; }
        public string account_number_description { get; set; }
        public Nullable<decimal> account_balance { get; set; }
    }
}
