//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTRServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApprovalMatrixLevelsDTO
    {
        public int role_level { get; set; }
        public int next_approval_level { get; set; }
        public decimal approval_limit { get; set; }
    }
}
