//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTRServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class available_balances
    {
        public int available_balance_key { get; set; }
        public Nullable<decimal> available_balance { get; set; }
    }
}
