//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTRServices
{
    using System;
    using System.Collections.Generic;

    public partial class TransferActivityBatchDTO
    {
        public string action { get; set; }
        public TransferActivityDTO transfer_activity {get; set;}
    }
}
