//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTRServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferActivityReviewerDTO
    {
        public int approval_key { get; set; }
        public int btr_key { get; set; }
        public int transfer_activity_key { get; set; }
        public int approval_matrix_key { get; set; }
        public int index_key { get; set; }
        public int account_key { get; set; }
        public int approver_uni_key { get; set; }
        public int role_level { get; set; }
        public int status_key { get; set; }
        public DateTime created { get; set; }
        public DateTime modified { get; set; }
        public Guid workflow_guid { get; set; }
        public string uni_name { get; set; }
        public string uni_email { get; set; }
        public string uni_code { get; set; }

    }
}
