
CREATE VIEW [dbo].[vw_Transactions] AS
SELECT  T.[transfer_activity_key]
      ,T.[type_key]
      ,T.[status_key]
      ,T.[approval_status_key]
      ,T.[index_key]
      ,T.[account_key]
      ,T.[activity_btr_guid]
      ,T.[activity_row_guid]
      ,T.[activity_item_guid]
      ,T.[activity_direction]
      ,T.[activity_number]
      ,T.[activity_line_number]
      ,T.[activity_explanation]
      ,T.[amount]
      ,T.[total_amount]
      ,T.[creation_user]
      ,T.[creation_date]
      ,T.[modify_user]
      ,T.[modify_date]
      ,T.[jv_doc_id]
      ,T.[jv_complete]
      ,T.[create_jv_error_message]
      ,T.[complete_jv_status_message]
	  ,i.[index_description]
	  ,i.[index_number_description]
	  ,a.[account_number]
	  ,a.[account_description]
	  ,a.[account_number_description]
	  ,a.[account_balance]

 FROM [dbo].[transfer_activity] t inner join [Index] i on t.index_key = i.index_key
  inner join Account a on t.[account_key] = a.[account_key] 

