//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTRServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public System.Guid transaction_item_id { get; set; }
        public int transfer_id { get; set; }
        public int row_id { get; set; }
        public string position { get; set; }
        public decimal amount { get; set; }
        public int index_key { get; set; }
        public int account_key { get; set; }
        public string approver_uni { get; set; }
    }
}
