//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTRServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_BudgetTransers
    {
        public int transfer_id { get; set; }
        public string budget_type { get; set; }
        public System.DateTime create_date { get; set; }
        public System.DateTime modified_date { get; set; }
        public string create_user { get; set; }
        public string modified_user { get; set; }
        public int status { get; set; }
    }
}
